### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [87yh97/Class#1]
1. Поместите ваш код в пакет.
2. Требовалось не дополнение до указанного множества, а дополнение до универсума (по сути инверсия), добавьте его тоже (старый метод можете оставить)
3. Можно делать несколько методов с разными типами аргументов, то есть, например addArrayOfElem и addElem можно переименовать в add.

**Comment by 87yh97** [comment]
Готово.

**Comment by gagarski** [comment]
Это задание готово, единственное, пакет принято называть с маленькой буквы, вариант второго сейчас вышлю на почту.
